spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    facade:
      count: 25
      lower-band: 1
      upper-band: 99
    http:
      client:
        config:
          uri: https://api.rand.by
          port: 80